[package]
name = "walk-assistant"
version = "0.1.0"
edition = "2024"

[dependencies]
rlua = "0.19.4"
eframe = "0.26"
egui = "0.26"
egui_plot = "0.26"
serialport = "4.3.0"
chrono = "0.4.34"
rfd = "0.15.3"
image = "0.25.5"

[build-dependencies]
winres = "0.1"